### ISSUE TITLE
Screenshot is broken on WordPress page

### ISSUE THREAD

**Issue by slaFFik** [spatie/myray.app#20]
URL: https://myray.app/docs/php/wordpress/getting-started

Page content: https://github.com/spatie/myray.app/blob/main/docs/php/wordpress/getting-started.md

The `src` of the image is `docs/ray/v1/images/wp-install.png` which doesn't exist.

**Comment by timvandijck** [comment]
@slaFFik thanks for letting us know, it should be back up now!
