### ISSUE TITLE
Docs missing for WordPress specific capabilities

### ISSUE THREAD

**Issue by Brugman** [spatie/myray.app#25]
The WordPress specific capabilities seem missing in the docs. They are referred and linked to on [the setup instructions page](https://myray.app/docs/php/wordpress/getting-started) and shown in the WP video:

![2024-06-20-00-22-01](https://github.com/spatie/myray.app/assets/2203813/b48b1c51-3552-4768-9721-cf14bf6f684b)

A [search](https://github.com/search?q=repo%3Aspatie%2Fmyray.app+showQueries%28%29&type=code) shows showQueries for example is never mentioned in a WordPress context, and showHooks is [not found at all](https://github.com/search?q=repo%3Aspatie%2Fmyray.app+showHooks&type=code).

I could browse [the source](https://github.com/spatie/wordpress-ray/blob/master/src/Loggers/QueryLogger.php) of the WP plugin, but I'd rather read your docs if you have them.

**Comment by freekmurze** [comment]
@timvandijck Could you create a new page WordPress > Usage on our docs site with this content: https://github.com/spatie/ray/blob/18f1303c0d4e8bffb96d45d09ff5667f75b89256/docs/usage/wordpress.md

**Comment by timvandijck** [comment]
Just added them back to the docs pages 👍
